version: '3.8'

services:
  app:
    container_name: sys_55003-app
    build:
      context: .
      dockerfile: Dockerfile
    image: sys_55003:latest
    ports:
      - "55003:55003"
    volumes:
      - ./uploads:/app/uploads
      - ./instance:/app/instance
      - ./flask_session:/app/flask_session
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:55003/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:14
    container_name: sys_55003-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sys_55003
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
